name: FC_Scan
description: Prueba de Scaning de texto y qr.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.1
  camera: ^0.10.5+2
  path: ^1.8.3
  path_provider: ^2.0.15
  html: ^0.15.4
  web_scraper: ^0.1.4
  google_ml_kit: ^0.16.2
  beautiful_soup_dart: ^0.3.0
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/fc_scan.png
    - assets/ml/
    - assets/images/

